window.AUTO_CHESS_DATA = {
  meta: {
    updatedLabel: "2026-07-08",
    sourceNote: "Unofficial fan reference. Build rankings are patch-informed interpretations. Reference data is generated from official Dragonest pages, explicit patch overrides, Steam news, and the local Steam game cache when available. Community-tagged builds come from recent r/AutoChess discussion and should be treated as meta signals to verify in your own lobbies.",
    patchNotes: {
      title: "MAINTENANCE on 26th March",
      date: "2026-03-25 Steam / 2026-03-26 UTC+8",
      sourceUrl: "https://store.steampowered.com/news/app/1530300/view/496097685470709756",
      highlights: [
        {
          title: "New Piece",
          items: [
            "Ronin-Nue added as a Rare Watcher/Assassin.",
            "Its active stuns one enemy and deals physical damage plus max-HP damage."
          ]
        },
        {
          title: "Talents",
          items: [
            "Talent choices now appear on rounds 5, 15, 25, and 35.",
            "Key late choices include Odd Call for Strange Eggs or Limit Break up to level 16."
          ]
        },
        {
          title: "Synergies",
          items: [
            "Watcher now adds extra targets to unit-targeted or item abilities cast on enemies.",
            "Druid can upgrade two identical 3-star Druids into a Super Strange Egg."
          ]
        },
        {
          title: "Items",
          items: [
            "Magicka Pendant converts the carrier's damage to magic damage.",
            "Four-Leaf Clover now lets Feathered and Assassin synergy effects benefit from item bonuses."
          ]
        }
      ]
    }
  },
  builds: [
    {
      id: "watcher-assassin",
      name: "Watcher Assassin",
      tier: "S",
      style: "Backline Pick",
      difficulty: "Hard",
      timing: "Level 7-8",
      score: 93,
      tags: ["Watcher", "Assassin", "Ronin-Nue"],
      winCondition: "Use Ronin-Nue as the new Rare Watcher/Assassin bridge, then win by chaining single-target disables onto carries through Watcher bonus targeting.",
      core: ["Ronin-Nue", "Shining Assassin", "Shadowcrawler", "Abyssalcrawler", "Soul Breaker", "Taboo Witcher", "Warpwood Sage", "Control flex"],
      early: ["Buy Ronin-Nue on sight if Assassin pieces are open", "Use any two-star front line until Feathered or Watcher pieces appear", "Scout corners every round after assassins are online"],
      items: ["Four-Leaf Clover if Feathered or Assassin bonuses are online", "Damage and crit on Shadowcrawler or Shining Assassin", "Defensive utility on the bait front line"],
      positioning: ["Jump Ronin-Nue toward the enemy carry corner", "Put bait opposite the carry you want to pull movement from", "Dodge Mithril Armor targets when trying to land targeted skills"],
      strongInto: ["Greedy caster boards", "Single-carry item comps", "Backlines without corner bait"],
      weakInto: ["Warrior armor", "Mithril Armor on the main target", "Spread boards with multiple disposable backliners"],
      counterPlan: ["Place bait pieces in both back corners", "Use Mithril Armor on the carry likely to be targeted", "Avoid putting every important unit in one jump lane"],
      punishWith: ["warrior-frontline", "druid-super-egg", "ogre-rage-casters"],
      pivots: ["Feathered Assassin", "Watcher Control", "Pure physical Assassin"],
      note: "Patch basis: Steam notes add Ronin-Nue as Watcher/Assassin and change Watcher so unit-targeted or item abilities cast on enemies can affect one additional target."
    },
    {
      id: "druid-super-egg",
      name: "Druid Super Egg",
      tier: "S",
      style: "Scaling Frontline",
      difficulty: "Hard",
      timing: "Round 25+",
      score: 91,
      tags: ["Druid", "Strange Egg", "Odd Call"],
      winCondition: "Build toward upgraded Druids and Strange Eggs, then use Super Strange Egg damage reduction and HP sharing to outlast burst boards.",
      core: ["Razorclaw", "Warpwood Sage", "Wisdom Defender", "Strange Egg", "Two identical 3-star Druids", "Soul Reaper", "Control flex", "Carry flex"],
      early: ["Hold Druids only when pairs are natural", "Choose Odd Call at round 35 if Strange Egg odds matter more than level cap", "Use the new relic skip option for 10-15 gold when relic choices do not fit"],
      items: ["Tank items on the unit protected by Strange Egg links", "War Horn on summoners if the line includes summons", "Mana on Soul Reaper or control flex"],
      positioning: ["Keep linked units inside Strange Egg range", "Do not clump so hard that one Mage cast decides the fight", "Move the Egg away from direct Assassin jump paths"],
      strongInto: ["Single-target damage", "Assassin burst after links form", "Long front-to-back fights"],
      weakInto: ["Huge AoE burst", "Early tempo pressure before 3-star Druids", "Magic conversion carries that bypass armor plans"],
      counterPlan: ["Punish the Druid player before round 35", "Use AoE to hit linked units together", "Break the formation by forcing Egg links onto low-value units"],
      punishWith: ["magicka-dragon", "watcher-assassin", "limit-break-legendary"],
      pivots: ["Summon War Horn", "Feathered Druid", "Legendary Sustain"],
      note: "Patch basis: Steam notes add a 3-star Strange Egg form and a Druid upgrade that turns two identical 3-star Druids into a Super Strange Egg."
    },
    {
      id: "ogre-rage-casters",
      name: "Ogre Rage Casters",
      tier: "A",
      style: "Spell Tempo",
      difficulty: "Medium",
      timing: "Level 7-8",
      score: 88,
      tags: ["Ogre Mage", "Rage", "Caster"],
      winCondition: "Use the reworked Rare Ogre Mage aura to give nearby allies extra-cast chances and stacking attack speed.",
      core: ["Ogre Mage", "Thunder Spirit", "Tortola Elder", "The Source", "Storm Shaman", "Ronin-Nue", "Soul Reaper", "Frontline flex"],
      early: ["Treat Ogre Mage as a real Rare pickup, not disposable filler", "Keep casters close enough to benefit from the aura", "Choose Elite Forces at round 15 if the shop odds matter more than discounts"],
      items: ["Mana on Tortola Elder or Storm Shaman", "Magicka Pendant on a physical piece when magic damage is the better damage profile", "Survival items on the aura cluster"],
      positioning: ["Cluster enough units in Ogre Mage aura without feeding full-board AoE", "Protect The Source", "Move casters away from Ronin-Nue jump angles"],
      strongInto: ["Slow front lines", "Boards without silence", "Comps that need one carry to survive"],
      weakInto: ["Assassin access to the aura cluster", "Marine or magic resistance stacking", "Mithril Armor on the target you need to disable"],
      counterPlan: ["Jump Ogre Mage or The Source before the first spell cycle", "Spread to reduce spell splash value", "Use silence on Berserker and active casters since Berserker can now be properly silenced"],
      punishWith: ["watcher-assassin", "egersis-hunter", "druid-super-egg"],
      pivots: ["Divinity Control", "Mage Control", "Watcher Caster"],
      note: "Patch basis: Ogre Mage moved from Common to Rare and now gives nearby allies a chance to cast abilities again while gaining Rage attack speed."
    },
    {
      id: "limit-break-legendary",
      name: "Limit Break Legendary",
      tier: "A",
      style: "Economy Cap",
      difficulty: "Hard",
      timing: "Round 35+",
      score: 86,
      tags: ["Talent", "Level 16", "Legendary"],
      winCondition: "Survive to round 35, choose Limit Break, then turn a larger board cap into overwhelming legendary and control density.",
      core: ["Soul Reaper", "Storm Shaman", "Tsunami Stalker", "Devastator", "Dragon Knight", "Rogue Guard", "Argali Knight", "Any discovered legendary"],
      early: ["Choose economy talents that match your health: Relentless Push when streaking, Quiet Reserve when losing", "At round 15 pick Honor the Worthy for reroll lines or Elite Forces for leveling lines", "Skip weak relic choices for 10-15 gold when economy is the real plan"],
      items: ["Mana on control legendaries", "Defensive items on the main front line", "Damage items on whichever late carry the match pool gives"],
      positioning: ["Spread extra units so the larger board is not one AoE target", "Layer control pieces across multiple rows", "Protect the carry that actually uses the added board space"],
      strongInto: ["Lobbies that let you preserve HP", "Low-pressure economy games", "Comps capped at level 9 or 10"],
      weakInto: ["Hard mid-game pressure", "Assassin snowball", "Odd Call Druid boards that outscale without leveling"],
      counterPlan: ["Pressure before round 35", "Deny win streaks so economy talents produce less value", "Force them to spend before Limit Break matters"],
      punishWith: ["watcher-assassin", "egersis-hunter", "druid-super-egg"],
      pivots: ["Legendary Sustain", "Dragon Legendary", "Ogre Rage Casters"],
      note: "Patch basis: Steam notes add the Talent System, including Limit Break at round 35 to unlock the level cap up to level 16."
    },
    {
      id: "magicka-dragon",
      name: "Magicka Dragon",
      tier: "A",
      style: "Magic Conversion",
      difficulty: "Medium",
      timing: "Item Dependent",
      score: 84,
      tags: ["Magicka Pendant", "Dragon", "Skill Damage"],
      winCondition: "Use Magicka Pendant to convert a high-output carrier into magic damage, while Dragon Knight splash now counting as skill damage opens stronger item and synergy interactions.",
      core: ["Dragon Knight", "Shining Dragon", "Venom", "Winter Chiropteran", "Tortola Elder", "The Source", "Storm Shaman", "Frontline flex"],
      early: ["Do not force without Dragon pieces or Magicka Pendant", "Play strongest upgraded front line until Dragon Knight appears", "Use Elite Forces if you need better odds at higher-cost pieces"],
      items: ["Magicka Pendant on the carrier that needs magic conversion", "Mana on Tortola Elder or Storm Shaman", "Defensive items on the first tank"],
      positioning: ["Keep Dragon Knight away from first disable", "Spread against Watcher-targeted skills", "Aim Storm Shaman into the enemy damage cluster"],
      strongInto: ["Armor-heavy Warriors", "Druid boards relying on armor and damage sharing", "Physical mitigation shells"],
      weakInto: ["Marine or magic resistance", "Assassin jumps", "Silence before first cast"],
      counterPlan: ["Stack magic resistance instead of armor", "Jump The Source or Dragon Knight", "Use Mithril Armor to negate key targeted setup skills"],
      punishWith: ["watcher-assassin", "egersis-hunter", "limit-break-legendary"],
      pivots: ["Dragon Mage", "Ogre Rage Casters", "Legendary Dragon"],
      note: "Patch basis: Magicka Pendant converts damage to magic damage, and Dragon Knight splash damage now counts as skill damage."
    },
    {
      id: "feather-clover",
      name: "Feather Clover",
      tier: "A",
      style: "Evasion Carry",
      difficulty: "Medium",
      timing: "Level 8",
      score: 83,
      tags: ["Feathered", "Assassin", "Four-Leaf Clover"],
      winCondition: "Leverage the Four-Leaf Clover adjustment so Feathered and Assassin synergy effects benefit from item bonuses.",
      core: ["Warpwood Sage", "Wisdom Defender", "Wind Ranger", "Shadowcrawler", "Shining Assassin", "Ronin-Nue", "Razorclaw", "Control flex"],
      early: ["Hold Feathered tanks with Assassin damage pairs", "Prioritize Four-Leaf Clover when offered", "Scout whether the lobby is building magic conversion or pure spell burst"],
      items: ["Four-Leaf Clover on the carry or synergy-critical unit", "Crit and attack speed on Shadowcrawler", "Tank items on Warpwood Sage"],
      positioning: ["Scout carry corners every round", "Split carries against Dragon and Mage boards", "Keep Feathered tanks where they can buy time for jumps"],
      strongInto: ["Hunter backlines", "Single-carry boards", "Physical teams without reliable spell damage"],
      weakInto: ["Magicka Pendant carries", "Large AoE magic", "Mithril Armor and baited target lines"],
      counterPlan: ["Use magic damage instead of physical accuracy checks", "Put expendable bait in both corners", "Disable the Clover holder before synergy value snowballs"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "warrior-frontline"],
      pivots: ["Watcher Assassin", "6 Feathered", "Druid Super Egg"],
      note: "Patch basis: Four-Leaf Clover now lets Feathered and Assassin synergy effects benefit from item bonuses."
    },
    {
      id: "egersis-hunter",
      name: "Egersis Hunter",
      tier: "B",
      style: "Ranged Physical",
      difficulty: "Medium",
      timing: "Level 8",
      score: 80,
      tags: ["Hunter", "Armor Shred", "Tempo"],
      winCondition: "Punish talent-greedy and Druid-greedy players before they reach Odd Call, Super Strange Egg, or Limit Break.",
      core: ["Dwarf Sniper", "Wind Ranger", "Egersis Ranger", "Egersis Prophet", "Tsunami Stalker", "Devastator", "Frontline flex", "Soul Reaper"],
      early: ["Use Hunter pairs with any upgraded tanks", "Choose Relentless Push when streaking", "Take Siphon at round 25 if your chessplayer damage plan needs lifesteal"],
      items: ["Damage on Dwarf Sniper", "Twin Fangs if multiple enemies share the same carry", "Mana on Tsunami Stalker or Devastator"],
      positioning: ["Corner Sniper with bait beside him", "Move corners every round into Assassin lobbies", "Keep control one row ahead of carries"],
      strongInto: ["Greedy leveling", "Druid setups before 3-stars", "Mage boards before they cast"],
      weakInto: ["Watcher Assassin jumps", "Cocoon damage reduction", "Strange Egg damage sharing"],
      counterPlan: ["Jump or target the Hunter backline", "Use Cocoon at round 25 if burst is the lobby problem", "Deploy Strange Egg or tank links to blunt focus fire"],
      punishWith: ["watcher-assassin", "druid-super-egg", "warrior-frontline"],
      pivots: ["Hunter Legendary", "Egersis Control", "Tempo into Limit Break"],
      note: "Patch basis: the Talent System creates more greed windows; Hunters remain useful as a pressure answer even without a direct patch buff."
    },
    {
      id: "warrior-frontline",
      name: "Warrior Frontline",
      tier: "B",
      style: "Stable Tempo",
      difficulty: "Easy",
      timing: "Level 7-8",
      score: 78,
      tags: ["Warrior", "Berserker", "Khan"],
      winCondition: "Use simple armor tempo to survive the new talent economy while deciding whether to push, reroll, or cap late.",
      core: ["Swordman", "Redaxe Chief", "Tusk Champion", "Pirate Captain", "Berserker", "Khan", "Doom Arbiter", "Carry flex"],
      early: ["Buy Warrior pairs and protect health", "Remember Berserker's active can now be silenced", "Treat Khan as a Rare tempo piece after the quality change"],
      items: ["Attack items on Berserker", "Tank items on Pirate Captain or Redaxe Chief", "Mithril Armor on the unit targeted by enemy skills"],
      positioning: ["Spread enough to avoid full Mage value", "Put Khan and Swordman where they influence the first contact", "Protect Berserker from direct silence if he is the carry"],
      strongInto: ["Assassins", "Physical tempo boards", "Unfinished Druid setups"],
      weakInto: ["Magicka Pendant", "Egersis armor reduction", "Caster chains with Ogre Mage"],
      counterPlan: ["Use magic conversion over armor", "Silence Berserker now that it works properly", "Do not let Warriors preserve enough health to reach Limit Break"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "egersis-hunter"],
      pivots: ["Limit Break Legendary", "Hunter Warrior", "Khan Tempo"],
      note: "Patch basis: Khan moved from Legendary to Rare with lower damage profile, and Berserker's ability changed to Active and can be silenced correctly."
    },
    {
      id: "watcher-control",
      name: "Watcher Control",
      tier: "B",
      style: "Targeted Utility",
      difficulty: "Hard",
      timing: "Level 8-9",
      score: 77,
      tags: ["Watcher", "Control", "Utility"],
      winCondition: "Stack unit-targeted disables and item effects so the Watcher change turns one key cast into multi-target disruption.",
      core: ["Ronin-Nue", "Unknown Horror", "Storm Shaman", "Soul Reaper", "Taboo Witcher", "Ogre Mage", "Frontline flex", "Carry flex"],
      early: ["Start from Ronin-Nue or Unknown Horror shops", "Do not force Watcher if the lobby has Mithril Armor everywhere", "Pick Elite Forces if higher-cost control pieces are the plan"],
      items: ["Targeted active items on reliable casters", "Mana on Storm Shaman or Soul Reaper", "Defensive items on the control front line"],
      positioning: ["Aim targeted skills away from bait units", "Spread to avoid losing all control pieces at once", "Move Ronin-Nue to threaten the highest-value target"],
      strongInto: ["Single carry comps", "Boards relying on one protected caster", "Low-bait backlines"],
      weakInto: ["Mithril Armor", "Wide summon boards", "Druid damage sharing"],
      counterPlan: ["Use expendable units to absorb extra targeted effects", "Put Mithril Armor on the high-value target", "Overwhelm with summons or linked Egg units"],
      punishWith: ["druid-super-egg", "summon-war-horn", "feather-clover"],
      pivots: ["Watcher Assassin", "Ogre Rage Casters", "Limit Break Legendary"],
      note: "Patch basis: Watcher's old +1 item ability effect was removed, then replaced with a broader extra-target effect for unit-targeted or item abilities cast on enemies."
    },
    {
      id: "summon-war-horn",
      name: "Summon War Horn",
      tier: "B",
      style: "Summon Pressure",
      difficulty: "Medium",
      timing: "Mid Game",
      score: 75,
      tags: ["Summon", "War Horn", "Tempo"],
      winCondition: "Use summon pressure as a practical answer to Watcher target lines and single-target carries, especially if the lobby lacks AoE.",
      core: ["Razorclaw", "Werewolf", "Poisonous Worm", "Tusk Champion", "Pirate Captain", "Berserker", "Soul Reaper", "Control flex"],
      early: ["Play summons when pairs are natural", "Choose Relentless Push if summons are preserving a streak", "Skip weak relic choices for gold when you need tempo"],
      items: ["War Horn on a reliable summoner", "Damage items on Berserker or carry flex", "Mana on Pirate Captain or Soul Reaper"],
      positioning: ["Leave room for summons", "Avoid clumping into Mage splash", "Put expendable summoned value between Watcher threats and your real carry"],
      strongInto: ["Single-target Watcher lines", "Hunter boards without AoE", "Low-damage stall comps"],
      weakInto: ["Dragon Mage", "Devastator", "Ogre caster chains"],
      counterPlan: ["Clear summons with AoE", "Kill summoners before War Horn value lands", "Use Strange Egg links so summons do not isolate priority targets"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "druid-super-egg"],
      pivots: ["Druid Super Egg", "Warrior Frontline", "Beast Warrior"],
      note: "Patch basis: not the headline of the Steam patch, but summon boards remain a useful counter-shape into the new Watcher single-target pressure."
    },
    {
      id: "insect-midgame-swarm",
      name: "Insect Midgame Swarm",
      tier: "A",
      style: "Community Meta",
      difficulty: "Medium",
      timing: "Mid Game",
      score: 85,
      tags: ["Insectoid", "Civet", "Summon", "Reddit"],
      winCondition: "Use the post-update Insect consistency to flood the mid game with extra bodies, then let summons and duplicate-piece pressure protect the real carry.",
      core: ["Civet", "Insectoid pair", "Duplicate non-Insect front line", "Poisonous Worm", "Razorclaw", "Werewolf", "Control flex", "Carry flex"],
      early: ["Hold duplicate non-Insect pairs when the Insect opener is natural", "Keep one duplicate safer so the dying copy can trigger swarm value", "Do not force it into lobbies already stacking AoE"],
      items: ["War Horn on a reliable summoner", "Tank items on the surviving duplicate or main front line", "Sustain or cleave on the real carry"],
      positioning: ["Split duplicate pairs so one dies first and one survives", "Leave board space for summons to matter", "Keep the real carry away from the first control lane"],
      strongInto: ["Single-target Watcher lines", "Hunters without AoE", "Greedy boards that need time to stabilize"],
      weakInto: ["Dragon Mage", "Ogre caster chains", "High-sustain Glacier or Warlock carries"],
      counterPlan: ["Use wide AoE to clear summons before they stall the fight", "Focus the surviving duplicate to deny repeated Insect value", "Bring lifesteal or spell lifesteal so summon chip damage feeds recovery"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "warrior-frontline"],
      pivots: ["Summon War Horn", "Beast Warrior", "Druid Super Egg"],
      note: "Community signal: recent r/AutoChess discussion says post-update Insect feels more consistent and easier through the mid game; treat this as a meta watch item rather than an official tier placement.",
      sourceLabel: "r/AutoChess: Insect synergy after update",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1tp05dl/insect_synergy_after_update/"
    },
    {
      id: "knight-cannon-granny",
      name: "Knight Cannon Granny",
      tier: "A",
      style: "Community Meta",
      difficulty: "Medium",
      timing: "Level 8-9",
      score: 84,
      tags: ["Knight", "Cannon Granny", "Carry", "Reddit"],
      winCondition: "Let the Knight shell buy enough time for Cannon Granny to shred the enemy front line and carry through sustained physical damage.",
      core: ["Cannon Granny", "Lightblade Knight", "Hell Knight", "Argali Knight", "Dragon Knight", "Soul Reaper", "Control flex", "Defensive support"],
      early: ["Play upgraded Knight pairs and preserve health", "Use any temporary ranged carry until Cannon Granny appears", "Scout for Egersis players before committing all damage items"],
      items: ["Attack speed and damage on Cannon Granny", "Tank items on the Knight most likely to take first contact", "Mana or control items on the support slot"],
      positioning: ["Keep Cannon Granny protected but not boxed in by low-value units", "Move the carry away from Assassin jump lanes", "Spread Knights enough to avoid one spell cycle deciding the round"],
      strongInto: ["Physical tempo boards", "Assassins that cannot reach the carry", "Low-burst front-to-back comps"],
      weakInto: ["Egersis armor reduction", "Magicka Pendant spell conversion", "Watcher jumps onto Cannon Granny"],
      counterPlan: ["Shred armor or bypass it with magic conversion", "Jump or target Cannon Granny before shields stabilize", "Use bait units so the Knight player cannot line up clean front-to-back damage"],
      punishWith: ["egersis-hunter", "magicka-dragon", "watcher-assassin"],
      pivots: ["Warrior Frontline", "Limit Break Legendary", "Dragon Knight Carry"],
      note: "Community signal: a recent r/AutoChess S36 post highlights Knight with Cannon Granny carry as a top meta threat; the source is title-level, so verify the exact final board in your own games.",
      sourceLabel: "r/AutoChess: Knight Cannon Granny S36",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1tgg9er/knight_is_the_most_broken_meta_in_s36_cannon/"
    },
    {
      id: "cave-divinity-mountain",
      name: "Cave Divinity Mountain",
      tier: "B",
      style: "Community Meta",
      difficulty: "Hard",
      timing: "Level 8-9",
      score: 81,
      tags: ["Cave Clan", "Divinity", "Mountain", "Reddit"],
      winCondition: "Combine a bulky Cave Clan core with Divinity tempo so Mountain can keep casting, soaking, and turning long fights.",
      core: ["Mountain", "Redaxe Chief", "Swordman", "Skull Hunter", "God of War", "God of Thunder", "The Source", "Storm Shaman"],
      early: ["Start from Cave Clan pairs when they are upgraded naturally", "Add Divinity pieces when the board can still support the synergy plan", "Keep an alternate Warrior or control line open if Mountain is contested"],
      items: ["Tank and sustain on Mountain", "Mana on The Source or Storm Shaman", "Damage on the temporary carry until Mountain is ready"],
      positioning: ["Put Mountain where he takes contact without being instantly isolated", "Protect The Source from backline jumps", "Shift Storm Shaman toward the enemy carry cluster"],
      strongInto: ["Low-burst physical boards", "Summon pressure without enough damage", "Assassins after Mountain is itemized"],
      weakInto: ["Egersis armor shred", "High-roll Legendary caps", "Pure magic burst before sustain begins"],
      counterPlan: ["Pressure it before the Cave and Divinity pieces are both online", "Use armor reduction or magic conversion instead of fighting through raw HP", "Jump The Source so the cooldown engine slows down"],
      punishWith: ["egersis-hunter", "magicka-dragon", "watcher-assassin"],
      pivots: ["Warrior Frontline", "Limit Break Legendary", "Ogre Rage Casters"],
      note: "Community signal: a recent r/AutoChess S36 post calls Cave Clan plus Divinity with Mountain carry back to meta; this entry is a practical sketch from the title signal, not a full written guide.",
      sourceLabel: "r/AutoChess: Cave Divinity Mountain S36",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1t63bsa/back_to_meta_in_s36_cave_clan_divinity_with/"
    },
    {
      id: "beast-shining-assassin",
      name: "6 Beast Shining Assassin",
      tier: "B",
      style: "Community Meta",
      difficulty: "Medium",
      timing: "Level 8",
      score: 80,
      tags: ["Beast", "Assassin", "Shining Assassin", "Reddit"],
      winCondition: "Use the 6 Beast damage engine and summon traffic to amplify Shining Assassin as the main backline killer.",
      core: ["Shining Assassin", "Tusk Champion", "Werewolf", "Razorclaw", "Poisonous Worm", "Unicorn", "Shadowcrawler", "Control flex"],
      early: ["Open with Beast pairs and any upgraded front line", "Hold Shining Assassin pieces without tanking your economy", "Use 3 Assassin as the bridge before the full Beast package is ready"],
      items: ["Damage, crit, and attack speed on Shining Assassin", "War Horn on a summoner when available", "Defensive utility on the unit most likely to bait control"],
      positioning: ["Jump Shining Assassin toward the highest-value backline target", "Leave room for summons to block enemy movement", "Move the carry every round into players holding targeted disables"],
      strongInto: ["Greedy caster boards", "Single-carry backlines", "Low-AoE Hunter setups"],
      weakInto: ["Warrior armor", "Mithril Armor and targeted control", "Dragon Mage splash"],
      counterPlan: ["Armor up and bait the Assassin jump", "Use AoE to remove summons before Beast damage stacks", "Disable Shining Assassin before she resets the fight"],
      punishWith: ["warrior-frontline", "watcher-control", "magicka-dragon"],
      pivots: ["Feather Clover", "Watcher Assassin", "Summon War Horn"],
      note: "Community signal: a recent r/AutoChess S36 post presents 6 Beast with Shining Assassin carry as an easy ranked build; source detail is title-level, so treat it as a lobby test candidate.",
      sourceLabel: "r/AutoChess: 6 Beast Shining Assassin S36",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1sqidks/easy_build_for_ranked_in_s36_6_beast_with_shining/"
    },
    {
      id: "god-thunder-mage",
      name: "God Thunder Mage",
      tier: "A",
      style: "Magic Burst",
      difficulty: "Hard",
      timing: "Level 9-10",
      score: 87,
      tags: ["Mage", "Divinity", "God of Thunder", "AoE", "Reddit"],
      winCondition: "Reach a late Mage board where God of Thunder, Tortola Elder, and control pieces chain enough AoE to erase clumped or armor-heavy boards.",
      core: ["God of Thunder", "Tortola Elder", "Thunder Spirit", "The Source", "Flame Wizard", "Winter Chiropteran", "Storm Shaman", "Frontline flex"],
      early: ["Open with Human Mage or strong two-star front line", "Use Priest or economy tools only if you can preserve enough HP for level 9", "Do not force the line if Marine players are already committed"],
      items: ["Mana and magic damage on God of Thunder or Tortola Elder", "Defensive item on the first tank", "Utility silence or control protection for The Source"],
      positioning: ["Spread casters enough to avoid Sandbound or Dragon splash", "Protect The Source from Assassin and Watcher access", "Aim Storm Shaman toward the enemy carry cluster"],
      strongInto: ["Warrior armor", "Feathered evasion", "Goblin and Mech front lines", "Insectoid boards without magic resistance"],
      weakInto: ["Marine magic resistance", "Assassin jumps onto The Source", "Human silence before the first cast", "Abyss Orb anti-mage tech"],
      counterPlan: ["Add Marine or magic resistance when Mage is the main lobby threat", "Jump or silence The Source before the first spell cycle", "Spread carries so God of Thunder and Tortola Elder do not hit the whole board"],
      punishWith: ["marine-assassin", "watcher-assassin", "dragon-witcher-rogue"],
      pivots: ["Ogre Rage Casters", "Dragon Mage", "Legendary Mage"],
      note: "Community signal: a recent r/AutoChess post and GMBX video title call out Mage with God of Thunder carry as a ranked build. Treat the exact unit mix as flexible around the local piece pool.",
      sourceLabel: "r/AutoChess: Mage God of Thunder",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1txdwmb/best_build_for_ranked_mage_with_god_of_thunder/"
    },
    {
      id: "insect-doom-arbiter",
      name: "Insectoid Doom Arbiter",
      tier: "A",
      style: "Swarm Carry",
      difficulty: "Hard",
      timing: "Level 8-9",
      score: 86,
      tags: ["Insectoid", "Doom Arbiter", "Swarm", "Demon", "Reddit"],
      winCondition: "Use Insectoid bodies to stall and dilute targeting while Doom Arbiter becomes the real damage threat behind the swarm.",
      core: ["Doom Arbiter", "Poisonous Worm", "Lord of Sand", "Thorn Predator", "Spider Queen", "Razorclaw", "Warpwood Sage", "Control flex"],
      early: ["Hold Insectoid pairs when the opener is natural", "Use Beast or Druid front line until Doom Arbiter appears", "Avoid over-rolling before the board has enough economy to finish the carry"],
      items: ["Damage and sustain on Doom Arbiter", "War Horn or summon value on Poisonous Worm or Razorclaw", "Armor or magic resistance on the front line based on lobby damage"],
      positioning: ["Keep Doom Arbiter protected behind disposable bodies", "Leave space for summons and Insectoid bodies to spawn", "Do not let one AoE spell hit every real unit and every summon"],
      strongInto: ["Single-target carry comps", "Watcher lines with limited AoE", "Hunter focus fire", "Boards that waste damage on summons"],
      weakInto: ["9 Mage or Dragon Mage AoE", "Devastator and Storm Shaman control", "Abyss Orb anti-mage or anti-carry tech", "Spread boards that deny Doom cleave"],
      counterPlan: ["Use wide AoE before the swarm can multiply", "Spread to reduce Doom Arbiter cleave value", "Control Doom Arbiter while killing the real Insectoid pieces rather than only summons"],
      punishWith: ["god-thunder-mage", "magicka-dragon", "ogre-rage-casters"],
      pivots: ["Insect Midgame Swarm", "Beast Shining Assassin", "Druid Super Egg"],
      note: "Community signal: a very recent S37 r/AutoChess post highlights Insectoid with Doom Arbiter carry. The counter notes also reflect a recent Insectoid-counter thread where Mage and Dragon Mage were mentioned as partial answers.",
      sourceLabel: "r/AutoChess: S37 Insectoid Doom",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1uf482u/the_most_toxic_build_in_s37_insectoid_with_doom/"
    },
    {
      id: "watcher-sand-doom",
      name: "Watcher Sand Doom",
      tier: "A",
      style: "Targeted Burst",
      difficulty: "Hard",
      timing: "Level 8-9",
      score: 85,
      tags: ["Watcher", "Sandbound", "Doom Arbiter", "Targeted", "Reddit"],
      winCondition: "Use Watcher extra-target logic with Sandbound-style targeting and Doom Arbiter pressure so enemy carries cannot hide behind one protected unit.",
      core: ["Hawk", "Ronin-Nue", "Lord of Sand", "Doom Arbiter", "Taboo Witcher", "Storm Shaman", "Soul Reaper", "Frontline flex"],
      early: ["Start only when Watcher pieces or Sandbound item access appears", "Use Lord of Sand as the bridge into Assassin or Insectoid pressure", "Scout for Marine and silence before committing all damage to the targeted line"],
      items: ["Sandbound Aegis on the unit enabling the targeted interaction", "Damage or sustain on Doom Arbiter", "Mana on Storm Shaman or Soul Reaper"],
      positioning: ["Aim Ronin-Nue and Lord of Sand toward the real carry side", "Avoid hitting only bait units by scouting corners", "Keep Doom Arbiter one row safer than the bait front line"],
      strongInto: ["Mage backlines with poor spacing", "Single-carry Hunters", "Knight boards relying on one protected Cannon Granny", "Greater or utility boards with a key enabler"],
      weakInto: ["Marine resistance plus spread positioning", "Summon boards with too many low-value targets", "Silence on the Sandbound holder", "Mithril Armor on the carry"],
      counterPlan: ["Spread pieces and add Marine when Sandbound Mage or Watcher targeting is the lobby problem", "Silence the Sandbound holder before the targeted hit lands", "Use expendable side units so Watcher effects do not chain onto the carry"],
      punishWith: ["marine-assassin", "summon-war-horn", "goblin-ancestor-warlock"],
      pivots: ["Watcher Assassin", "Watcher Control", "Insectoid Doom Arbiter"],
      note: "Community signal: an S36 r/AutoChess post calls out 4 Watcher with Sandbound and Doom, and a separate counter thread recommends spreading and Marine against Sandbound Mage pressure.",
      sourceLabel: "r/AutoChess: Watcher Sandbound Doom",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1sep7fs/the_new_meta_in_s36_4_watcher_with_sandbound_and/"
    },
    {
      id: "glacier-warlock",
      name: "6 Glacier 4 Warlock",
      tier: "B",
      style: "Sustain DPS",
      difficulty: "Medium",
      timing: "Level 8-9",
      score: 82,
      tags: ["Glacier", "Warlock", "Sustain", "Attack Speed", "Reddit"],
      winCondition: "Stack Glacier attack speed with Warlock sustain so a protected carry keeps healing through long fights.",
      core: ["Berserker", "Sacred Lancer", "Frost Knight", "Defector", "Desperate Doctor", "Fortune Teller", "Soul Reaper", "Dark Spirit"],
      early: ["Use Glacier pairs only when they upgrade naturally", "Bridge with Knights or Warriors until the Warlock sustain is online", "Avoid forcing if the lobby has heavy burst and backline access"],
      items: ["Damage and attack speed on Berserker or Sacred Lancer", "Defensive sustain on the main front line", "Mana on Soul Reaper or Dark Spirit"],
      positioning: ["Keep the main carry behind a second body, not exposed in the corner", "Spread against Mage and Dragon openers", "Move the carry away from Ronin-Nue and Assassin lanes"],
      strongInto: ["Chip damage", "Low-burst Warrior boards", "Summon boards without enough AoE", "Tempo comps that cannot finish targets"],
      weakInto: ["Mage burst before lifesteal starts", "Assassin access to the carry", "Hard silence or hex on Berserker/Sacred Lancer", "Egersis armor pressure"],
      counterPlan: ["Burst or disable the Glacier carry before Warlock healing starts", "Use armor reduction if the carry is physical and itemized", "Spread control so one sustain unit cannot free-fire"],
      punishWith: ["watcher-assassin", "god-thunder-mage", "egersis-hunter"],
      pivots: ["Knight Cannon Granny", "Warrior Frontline", "Dragon Witcher Rogue"],
      note: "Community signal: r/AutoChess S35 content highlighted 6 Glacier 4 Warlock as a meta shell. It is included as a sustain counter-template rather than a guaranteed current top comp.",
      sourceLabel: "r/AutoChess: 6 Glacier 4 Warlock",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1qy8lyj/the_new_meta_in_season_35_6_glacier_4_warlock/"
    },
    {
      id: "goblin-ancestor-warlock",
      name: "Goblin Ancestor Warlock",
      tier: "B",
      style: "Reroll Sustain",
      difficulty: "Medium",
      timing: "Reroll into Level 8+",
      score: 81,
      tags: ["Goblin", "Ancestor", "Warlock", "Reroll", "Community Guide"],
      winCondition: "Reroll early Goblins into a durable board, then add Ancestor and Warlock value so the board survives long enough for carries to scale.",
      core: ["Heaven Bomber", "Sky Breaker", "Soul Breaker", "Ripper", "Venomancer", "Devastator", "Penitent Bishop", "Soul Reaper"],
      early: ["Do not level early if you are rerolling 1-cost Goblins", "Prioritize economy and piece-stacking relics", "Use Priest loss streak only when both Priest pieces are available"],
      items: ["Mana and magic damage on Heaven Bomber", "Tank and utility on the main Goblin front line", "Warlock or sustain items on the late carry"],
      positioning: ["Let Goblins take first contact while backline carries stay separated", "Place Penitent Bishop where the curse reaches an enemy carry", "Swap Ripper out when stronger Goblin or Mech pieces arrive"],
      strongInto: ["Assassin pressure", "Hunter focus fire", "Physical tempo", "Low-AoE summon boards"],
      weakInto: ["Mage burst", "Late Insectoid pivots", "Witcher or pure-damage caps", "Lobbies that punish slow reroll economy"],
      counterPlan: ["Use Mage or Insectoid pivots before the Goblin player finishes the cap", "Do not feed them free winstreaks while they reroll", "Kill backline carries instead of wasting every hit into high-regen Goblins"],
      punishWith: ["god-thunder-mage", "insect-doom-arbiter", "dragon-witcher-rogue"],
      pivots: ["Goblin Mech", "6 Goblin 4 Warlock", "Limit Break Legendary"],
      note: "Community guide signal: a January 2026 6 Goblin/Ancient guide describes the reroll plan, carry options, Warlock add-in, and low-level progression. A Reddit discussion also notes Mage and late Insect as counters.",
      sourceLabel: "Kinpira guide: 6 Goblin 4 Ancient",
      sourceUrl: "https://note.com/kinpira_pirapira/n/n5a67d4f4d900?hl=en"
    },
    {
      id: "dragon-witcher-rogue",
      name: "Dragon Witcher Rogue",
      tier: "B",
      style: "Late Pure Damage",
      difficulty: "Hard",
      timing: "Late Game Pivot",
      score: 80,
      tags: ["Dragon", "Witcher", "Rogue Guard", "Demon", "Late Tech"],
      winCondition: "Pivot into Dragon and Witcher once Rogue Guard appears, then use pure-damage pressure to punish high-defense late boards.",
      core: ["Rogue Guard", "Dragon Knight", "Frostblaze Dragon", "Umbra", "Venom", "Taboo Witcher", "Fallen Witcher", "Resentful Murk"],
      early: ["Do not force this before Rogue Guard or Dragon Knight appears", "Use Hunters, Warriors, or Dragons as the bridge", "Hold Witchers only when they do not wreck your economy"],
      items: ["Damage and survival on Rogue Guard or Dragon Knight", "Mana or utility on Frostblaze Dragon", "Defensive items on the unit taking first contact"],
      positioning: ["Protect Rogue Guard from first hex or stun", "Spread Dragons so one Mage cast does not remove the whole setup", "Move Witchers away from expendable bait lanes"],
      strongInto: ["Knights", "Warriors", "Horn mitigation", "Marine boards relying on resistance", "Single oversized melee carries"],
      weakInto: ["Insectoid overwhelm", "Hard hex or disarm on Rogue Guard", "High-tempo players before the pivot", "Mage burst if Rogue Guard is not online"],
      counterPlan: ["Use summons or Insectoid bodies to waste Rogue Guard damage", "Hex, disarm, or stun Rogue Guard before he starts cleaving", "Nuke or control the carry before Dragon/Witcher value stabilizes"],
      punishWith: ["insect-doom-arbiter", "god-thunder-mage", "summon-war-horn"],
      pivots: ["Limit Break Legendary", "Dragon Mage", "6 Warrior 4 Witcher"],
      note: "Older but useful meta signal: an r/AutoChess ranked tier list described 5 Dragon 4 Witcher as a late-game build that needs Rogue Guard, with Rogue Guard or Dragon Knight as carry. We keep it as a late-tech counter template.",
      sourceLabel: "r/AutoChess: S27 ranked tier list",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1figsy8/s27_ranked_tier_list/"
    },
    {
      id: "marine-assassin",
      name: "Marine Assassin",
      tier: "B",
      style: "Anti-Mage Access",
      difficulty: "Medium",
      timing: "Level 8-9",
      score: 79,
      tags: ["Marine", "Assassin", "Magic Resistance", "Backline Access"],
      winCondition: "Use Marine resistance to survive spell burst while Assassins reach the caster or carry line before the second cast cycle.",
      core: ["Abyssalcrawler", "Abyssal Guard", "Siren", "Tsunami Stalker", "Shining Assassin", "Shadowcrawler", "Ronin-Nue", "Soul Breaker"],
      early: ["Start from Assassin pairs or Marine pieces, not both at once", "Add Marine when Mage or Sandbound spell pressure is the lobby problem", "Keep a non-Assassin front line until the jumpers have upgrades"],
      items: ["Damage and crit on Shining Assassin or Shadowcrawler", "Mana on Siren or Tsunami Stalker", "Defensive utility on Abyssal Guard"],
      positioning: ["Jump toward The Source, God of Thunder, or the Sandbound holder", "Keep one bait unit in each corner against enemy Assassins", "Do not clump Marines into one Mage splash zone"],
      strongInto: ["Mage burst", "Dragon Mage", "Sandbound Mage", "Caster boards without enough bait"],
      weakInto: ["Warrior armor", "Knight shields", "Summon boards that absorb jumps", "Feathered evasion if spell follow-up is low"],
      counterPlan: ["Use armor and bait against the Assassin half", "Shift carries away from the Marine Assassin jump side", "Punish the board with physical frontline damage instead of relying only on spells"],
      punishWith: ["warrior-frontline", "knight-cannon-granny", "summon-war-horn"],
      pivots: ["Watcher Assassin", "Marine Hunter", "6 Assassin"],
      note: "Counter-template signal: recent Sandbound-counter discussion recommends spreading and adding Marine; older Marine Assassin content supports the anti-mage access shell.",
      sourceLabel: "r/AutoChess: Sandbound counter discussion",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1szx0ua/how_to_counter/"
    },
    {
      id: "feathered-wizard",
      name: "9 Feathered Wizard",
      tier: "A",
      style: "Evasion Cap",
      difficulty: "Hard",
      timing: "Level 9-10",
      score: 86,
      tags: ["Feathered", "Wizard", "Evasion", "Community Meta"],
      winCondition: "Use Wizard shortcut value to reach a high Feathered breakpoint, then let evasion and a protected Feathered carry win physical matchups.",
      core: ["Taboo Witcher", "Light Blade", "Wisper Seer", "Shining Archer", "Qin Xuan", "Warpwood Sage", "Wind Ranger", "Shadowcrawler", "Shining Assassin", "Grand Herald"],
      early: ["Open with Feathered pairs only when they upgrade naturally", "Hold Wizard pieces when they preserve the 9 Feathered cap without tanking economy", "Scout for Mage and Magicka Pendant before committing every defensive item to evasion"],
      items: ["Attack speed and damage on Shadowcrawler or Shining Assassin", "Tank items on Warpwood Sage", "Anti-magic or survival items if Mage players are present"],
      positioning: ["Use Feathered tanks to buy time for the carry", "Keep the main carry away from Assassin jump corners", "Spread against Mage and Dragon splash because evasion will not save clumped units"],
      strongInto: ["Hunters", "Warriors without magic conversion", "Physical tempo", "Dwarf backlines that lack spell follow-up"],
      weakInto: ["God Thunder Mage", "Magicka Dragon", "Shaman Mage control", "Marine-resistant boards with enough physical damage"],
      counterPlan: ["Use spell or magic damage instead of physical accuracy checks", "Control the Feathered carry before evasion stalls the fight", "Spread so Feathered Assassins cannot hit every carry lane cleanly"],
      punishWith: ["god-thunder-mage", "magicka-dragon", "shaman-mage-horn"],
      pivots: ["Feather Clover", "Watcher Assassin", "Druid Super Egg"],
      note: "Community signal: a recent r/AutoChess discussion calls 9 Feathered plus 3 Wizard one of the easiest current-meta win paths; older meta discussion also lists 9 Feathered as a consistent build.",
      sourceLabel: "r/AutoChess: current state discussion",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1r853lr/the_current_state_of_this_game_right_now/"
    },
    {
      id: "assassin-horn",
      name: "9 Assassin Horn",
      tier: "A",
      style: "Backline Burst",
      difficulty: "Hard",
      timing: "Level 8-10",
      score: 84,
      tags: ["Assassin", "Horn", "Backline Access", "Community Meta"],
      winCondition: "Cap Assassin damage while using Horn or defensive utility to keep the jumpers alive long enough to finish the carry line.",
      core: ["Shining Assassin", "Shadowcrawler", "Ronin-Nue", "Lord of Sand", "Abyssalcrawler", "Thorn Predator", "Water Spirit", "Phantom Queen", "Soul Breaker", "Khan"],
      early: ["Start from upgraded Assassins and only chase 9 when shops cooperate", "Use Khan or a temporary front line to avoid bleeding out before the cap", "Roll for key 3-star jumpers when level 7-8 shops are favorable"],
      items: ["Crit, attack speed, and damage on Shining Assassin or Shadowcrawler", "Defensive aura or Horn value on Khan/frontline", "Mana or utility on Ronin-Nue for targeted control"],
      positioning: ["Mirror jumpers toward the scouted carry side", "Keep one bait unit in each back corner against enemy Assassins", "Move Shining Assassin every round when opponents start baiting jump lanes"],
      strongInto: ["Mage backlines", "Hunter and Dwarf carries", "Divinity engines before control layers", "Single-carry Warlock boards"],
      weakInto: ["9 Warrior Rogue Guard", "Druid Super Egg", "Summon and Insectoid body floods", "Mithril Armor or corner bait on the real carry"],
      counterPlan: ["Use armor, bait corners, and wide front lines to absorb jumps", "Put expendable units in the first jump lane", "Control Shining Assassin before resets or crit chains start"],
      punishWith: ["warrior-rogue-guard", "druid-super-egg", "summon-war-horn"],
      pivots: ["Watcher Assassin", "Marine Assassin", "Feathered Wizard"],
      note: "Community signal: recent r/AutoChess current-state discussion calls 9 Assassin/Horn pretty good, while older 9-piece synergy discussion says 9 Assassin works well with shortcut/flex support.",
      sourceLabel: "r/AutoChess: current state discussion",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1r853lr/the_current_state_of_this_game_right_now/"
    },
    {
      id: "warrior-rogue-guard",
      name: "9 Warrior Rogue Guard",
      tier: "A",
      style: "Armor Cap",
      difficulty: "Medium",
      timing: "Level 9-10",
      score: 83,
      tags: ["Warrior", "Rogue Guard", "Armor", "Community Meta"],
      winCondition: "Stack the Warrior cap, then turn Rogue Guard or Berserker into the durable damage source that physical boards cannot cut through.",
      core: ["Rogue Guard", "Berserker", "Sacred Lancer", "Pirate Captain", "Doom Arbiter", "God of War", "Abyssal Guard", "Swordman", "Redaxe Chief", "Tusk Champion"],
      early: ["Use Warrior pairs to protect HP", "Do not greed for every Warrior if Mage players are streaking", "Pivot to Rogue Guard or Berserker based on which carry upgrades first"],
      items: ["Damage and lifesteal on Rogue Guard or Berserker", "Mana on Pirate Captain or Tsunami-style control flex", "Magic resistance if the lobby is spell-heavy"],
      positioning: ["Spread the front line so one Mage spell does not remove all armor value", "Put Rogue Guard where he hits carries after first contact", "Keep control pieces close enough to cast before Assassins wrap around"],
      strongInto: ["Assassins", "Beast summons", "Physical Hunters", "Greater mid-game boards"],
      weakInto: ["Egersis armor reduction", "Magicka Pendant", "God Thunder Mage", "Pure-damage Witcher pivots"],
      counterPlan: ["Use magic conversion or armor shred instead of basic physical trades", "Deny Rogue Guard first contact with bait and control", "Pressure before the Warrior player finds the late legendary carry"],
      punishWith: ["egersis-pact", "god-thunder-mage", "dragon-witcher-rogue"],
      pivots: ["Warrior Frontline", "Limit Break Legendary", "Dragon Witcher Rogue"],
      note: "Community signal: a r/AutoChess legendary-pool discussion says 9 Warrior is okay, but 9 Warrior with Rogue Guard or Berserker is really good. Greater-counter discussion also recommends 9 Warrior as a mid-game answer.",
      sourceLabel: "r/AutoChess: legendary pool discussion",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1kyjjqn/whats_the_point_of_hiding_half_of_the_legendary/"
    },
    {
      id: "divinity-warlock",
      name: "Divinity Warlock",
      tier: "B",
      style: "Cooldown Sustain",
      difficulty: "Hard",
      timing: "Level 8-10",
      score: 82,
      tags: ["Divinity", "Warlock", "Sustain", "Community Meta"],
      winCondition: "Use Divinity cooldown pressure with Warlock sustain so repeated casts and healing win fights that ordinary front lines cannot finish.",
      core: ["God of War", "Goddess of Light", "Grand Herald", "Khan", "God of Thunder", "Soul Reaper", "Desperate Doctor", "Dark Spirit", "Poisonous Worm", "Control flex"],
      early: ["Preserve HP with any upgraded front line until Divinity pieces appear", "Avoid activating conflicting race synergies if they turn off the Divinity plan", "Use Warlock only when the board has enough damage to make healing matter"],
      items: ["Mana on God of Thunder or Dark Spirit", "Defensive items on God of War or Khan", "Sustain and utility on Soul Reaper"],
      positioning: ["Protect God of Thunder and Grand Herald from jumpers", "Keep Warlocks spread so one silence does not stop all sustain", "Place God of War where he absorbs first contact without isolating the backline"],
      strongInto: ["Slow Warrior boards", "Goblin sustain", "Cave front lines", "Summon boards without burst"],
      weakInto: ["Assassin access", "Human silence", "Hard anti-heal or burst before Warlock value starts", "Marine Assassin reaching the caster line"],
      counterPlan: ["Jump or silence the Divinity engine pieces", "Burst one side before Warlock lifesteal stabilizes", "Pressure the build before it finishes both cooldown and sustain pieces"],
      punishWith: ["watcher-assassin", "marine-assassin", "assassin-horn"],
      pivots: ["God Thunder Mage", "Glacier Warlock", "Limit Break Legendary"],
      note: "Community signal: older r/AutoChess meta discussion lists Divinity Warlock alongside 9 Feathered and 9 Assassin as one of the most consistent builds. Kept here as a relevant sustain/cooldown template.",
      sourceLabel: "r/AutoChess: Feb 2024 meta discussion",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1aptv4j/meta_feb_2024/"
    },
    {
      id: "egersis-pact",
      name: "9 Egersis Pact",
      tier: "B",
      style: "Armor Shred Cap",
      difficulty: "Hard",
      timing: "Level 9+",
      score: 81,
      tags: ["Egersis", "Armor Shred", "Pact", "Community Meta"],
      winCondition: "Use Egersis Pact or shortcut support to reach the high Egersis breakpoint, then let armor reduction make even tank caps melt.",
      core: ["Egersis Ranger", "Resentful Murk", "Winter Chiropteran", "Eclipse of Darkness", "Ghost Kid", "Umbra", "Evil Knight", "Soul Reaper", "Grand Herald", "Carry flex"],
      early: ["Do not force 9 Egersis without Pact or a real shortcut", "Bridge with Egersis Hunter or Evil Knight tempo", "Watch for Strange Egg interactions because community comments flagged Pact inconsistencies"],
      items: ["Physical damage on Umbra or Egersis Ranger", "Mana on Soul Reaper", "Defensive utility on the front line that lives longest"],
      positioning: ["Keep armor-shred pieces alive long enough for the fight to turn", "Use Ghost Kid or Evil Knight as the first contact pocket", "Spread against Mage because Egersis does not solve spell burst"],
      strongInto: ["Knights", "Warriors", "Horn mitigation", "Cave HP walls", "Marine boards relying on resistance instead of armor"],
      weakInto: ["Mage burst", "Feathered evasion with spell follow-up", "Assassin access to Egersis Ranger", "Druid Super Egg damage sharing"],
      counterPlan: ["Use magic burst or evasion instead of armor stacking", "Jump the Egersis damage source", "Avoid letting one tank take every reduced-armor hit"],
      punishWith: ["god-thunder-mage", "feathered-wizard", "watcher-assassin"],
      pivots: ["Egersis Hunter", "Dragon Witcher Rogue", "Limit Break Legendary"],
      note: "Community signal: a recent S35 guide post highlights 9 Egersis, with comments noting Egersis Pact interaction issues to verify in-game. This entry is a high-breakpoint counter template, not a blind-force recommendation.",
      sourceLabel: "r/AutoChess: 9 Egersis S35 guide",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1s278um/how_to_play_9_egersis_in_s35_easy_guide_auto_chess/"
    },
    {
      id: "shaman-mage-horn",
      name: "Shaman Mage Horn",
      tier: "B",
      style: "Anti-Greater Control",
      difficulty: "Hard",
      timing: "Level 8-9",
      score: 80,
      tags: ["Shaman", "Mage", "Horn", "Control", "Community Counter"],
      winCondition: "Use Shaman disruption, Mage burst, and Horn durability to survive Greater-style CC and punish squishy backlines afterward.",
      core: ["Storm Shaman", "The Scryer", "Defector", "Khan", "Tortola Elder", "Thunder Spirit", "The Source", "God of Thunder", "Frontline flex"],
      early: ["Bridge from Cave Shaman, Mage pairs, or any upgraded front line", "Add Horn when the enemy plan relies on CC or burst windows", "Do not clump every caster around The Source into one jump lane"],
      items: ["Mana on Storm Shaman, The Scryer, or God of Thunder", "Tank items on Khan or the first-contact unit", "Magic damage on Tortola Elder or Thunder Spirit"],
      positioning: ["Spread against Greater, Mage, and Dragon splash", "Aim Shaman control into the carry cluster", "Keep Khan close enough to protect the caster pocket without dragging every spell into one tile"],
      strongInto: ["Greater", "Beast bruisers", "Warrior boards without Marine", "Summon boards that cannot survive repeated AoE"],
      weakInto: ["Marine magic resistance", "Assassin jump lanes", "Human silence before the first Shaman cast", "Egersis pressure killing the front line too quickly"],
      counterPlan: ["Add Marine or direct backline access", "Silence Storm Shaman or The Source", "Spread so Shaman/Mage control cannot hit every important unit at once"],
      punishWith: ["marine-assassin", "human-knight-marine", "watcher-assassin"],
      pivots: ["God Thunder Mage", "Ogre Rage Casters", "Cave Divinity Mountain"],
      note: "Community signal: Greater-counter discussion lists Shaman Mage, Mage Dragon, 9 Warrior, Horn, Warlock/Marine, and spread positioning as practical answers. This entry focuses the Shaman Mage + Horn branch.",
      sourceLabel: "r/AutoChess: Greater counter discussion",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1e8l9th/counters_for_the_greater/"
    },
    {
      id: "human-knight-marine",
      name: "Human Knight Marine",
      tier: "B",
      style: "Anti-Mage Tempo",
      difficulty: "Medium",
      timing: "Level 7-9",
      score: 79,
      tags: ["Human", "Knight", "Marine", "Anti-Mage", "Community Counter"],
      winCondition: "Use Human/Knight tempo to compete early while Marine and Cave-style durability stop Mage boards from one-cycling the fight.",
      core: ["Argali Knight", "Dragon Knight", "Light Blade", "Hell Knight", "Pirate Captain", "The Source", "Abyssal Guard", "Siren", "Tsunami Stalker", "Redaxe Chief"],
      early: ["Play to win rounds instead of greedily waiting for the final board", "Take Human/Knight pairs when they naturally 2-star", "Add 2 Marine or 2 Cave as soon as Mage pressure becomes obvious"],
      items: ["Tank items on the Knight front line", "Damage on Dragon Knight or the current upgraded carry", "Mana on Siren, Tsunami Stalker, or Pirate Captain"],
      positioning: ["Spread Knights against Mage splash", "Keep Marine control away from Assassin corners", "Use Pirate Captain or Siren to interrupt the first cast cycle"],
      strongInto: ["Human Mage", "Dragon Mage", "Low-tempo caster lobbies", "Assassins without enough armor shred"],
      weakInto: ["Egersis armor reduction", "Watcher targeted disables", "Insectoid body floods", "Late pure-damage Witcher pivots"],
      counterPlan: ["Shred the Knight armor or bypass it with pure damage", "Jump the Marine control before it casts", "Do not let the Human/Knight player streak freely through rounds 3-25"],
      punishWith: ["egersis-pact", "watcher-sand-doom", "insect-doom-arbiter"],
      pivots: ["Knight Cannon Granny", "Marine Assassin", "Limit Break Legendary"],
      note: "Community signal: a Human Mage counter discussion recommends Human/Knight with 2 Marine and/or 2 Cave, and another reply summarizes the idea as Knights/Human/Marine.",
      sourceLabel: "r/AutoChess: Human Mage counter discussion",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1b0pvlc/human_mage_exhausted/"
    }
  ]
};
