window.AUTO_CHESS_DATA = {
  meta: {
    updatedLabel: "2026-07-08",
    sourceNote: "Unofficial fan reference. Build rankings are patch-informed interpretations; patch facts are summarized from the official Auto Chess Steam news post MAINTENANCE on 26th March, shown on Steam as the March 25, 2026 update. Community-tagged builds come from recent r/AutoChess discussion and should be treated as meta signals to verify in your own lobbies.",
    patchNotes: {
      title: "MAINTENANCE on 26th March",
      date: "2026-03-25 Steam / 2026-03-26 UTC+8",
      sourceUrl: "https://store.steampowered.com/news/app/1530300/view/496097685470709756",
      highlights: [
        {
          title: "New Piece",
          items: [
            "Ronin-Nue added as a Rare Watcher/Assassin.",
            "Its active stuns one enemy and deals physical damage plus max-HP damage."
          ]
        },
        {
          title: "Talents",
          items: [
            "Talent choices now appear on rounds 5, 15, 25, and 35.",
            "Key late choices include Odd Call for Strange Eggs or Limit Break up to level 16."
          ]
        },
        {
          title: "Synergies",
          items: [
            "Watcher now adds extra targets to unit-targeted or item abilities cast on enemies.",
            "Druid can upgrade two identical 3-star Druids into a Super Strange Egg."
          ]
        },
        {
          title: "Items",
          items: [
            "Magicka Pendant converts the carrier's damage to magic damage.",
            "Four-Leaf Clover now lets Feathered and Assassin synergy effects benefit from item bonuses."
          ]
        }
      ]
    }
  },
  builds: [
    {
      id: "watcher-assassin",
      name: "Watcher Assassin",
      tier: "S",
      style: "Backline Pick",
      difficulty: "Hard",
      timing: "Level 7-8",
      score: 93,
      tags: ["Watcher", "Assassin", "Ronin-Nue"],
      winCondition: "Use Ronin-Nue as the new Rare Watcher/Assassin bridge, then win by chaining single-target disables onto carries through Watcher bonus targeting.",
      core: ["Ronin-Nue", "Shining Assassin", "Shadowcrawler", "Abyssalcrawler", "Soul Breaker", "Taboo Witcher", "Warpwood Sage", "Control flex"],
      early: ["Buy Ronin-Nue on sight if Assassin pieces are open", "Use any two-star front line until Feathered or Watcher pieces appear", "Scout corners every round after assassins are online"],
      items: ["Four-Leaf Clover if Feathered or Assassin bonuses are online", "Damage and crit on Shadowcrawler or Shining Assassin", "Defensive utility on the bait front line"],
      positioning: ["Jump Ronin-Nue toward the enemy carry corner", "Put bait opposite the carry you want to pull movement from", "Dodge Mithril Armor targets when trying to land targeted skills"],
      strongInto: ["Greedy caster boards", "Single-carry item comps", "Backlines without corner bait"],
      weakInto: ["Warrior armor", "Mithril Armor on the main target", "Spread boards with multiple disposable backliners"],
      counterPlan: ["Place bait pieces in both back corners", "Use Mithril Armor on the carry likely to be targeted", "Avoid putting every important unit in one jump lane"],
      punishWith: ["warrior-frontline", "druid-super-egg", "ogre-rage-casters"],
      pivots: ["Feathered Assassin", "Watcher Control", "Pure physical Assassin"],
      note: "Patch basis: Steam notes add Ronin-Nue as Watcher/Assassin and change Watcher so unit-targeted or item abilities cast on enemies can affect one additional target."
    },
    {
      id: "druid-super-egg",
      name: "Druid Super Egg",
      tier: "S",
      style: "Scaling Frontline",
      difficulty: "Hard",
      timing: "Round 25+",
      score: 91,
      tags: ["Druid", "Strange Egg", "Odd Call"],
      winCondition: "Build toward upgraded Druids and Strange Eggs, then use Super Strange Egg damage reduction and HP sharing to outlast burst boards.",
      core: ["Razorclaw", "Warpwood Sage", "Wisdom Defender", "Strange Egg", "Two identical 3-star Druids", "Soul Reaper", "Control flex", "Carry flex"],
      early: ["Hold Druids only when pairs are natural", "Choose Odd Call at round 35 if Strange Egg odds matter more than level cap", "Use the new relic skip option for 10-15 gold when relic choices do not fit"],
      items: ["Tank items on the unit protected by Strange Egg links", "War Horn on summoners if the line includes summons", "Mana on Soul Reaper or control flex"],
      positioning: ["Keep linked units inside Strange Egg range", "Do not clump so hard that one Mage cast decides the fight", "Move the Egg away from direct Assassin jump paths"],
      strongInto: ["Single-target damage", "Assassin burst after links form", "Long front-to-back fights"],
      weakInto: ["Huge AoE burst", "Early tempo pressure before 3-star Druids", "Magic conversion carries that bypass armor plans"],
      counterPlan: ["Punish the Druid player before round 35", "Use AoE to hit linked units together", "Break the formation by forcing Egg links onto low-value units"],
      punishWith: ["magicka-dragon", "watcher-assassin", "limit-break-legendary"],
      pivots: ["Summon War Horn", "Feathered Druid", "Legendary Sustain"],
      note: "Patch basis: Steam notes add a 3-star Strange Egg form and a Druid upgrade that turns two identical 3-star Druids into a Super Strange Egg."
    },
    {
      id: "ogre-rage-casters",
      name: "Ogre Rage Casters",
      tier: "A",
      style: "Spell Tempo",
      difficulty: "Medium",
      timing: "Level 7-8",
      score: 88,
      tags: ["Ogre Mage", "Rage", "Caster"],
      winCondition: "Use the reworked Rare Ogre Mage aura to give nearby allies extra-cast chances and stacking attack speed.",
      core: ["Ogre Mage", "Thunder Spirit", "Tortola Elder", "The Source", "Storm Shaman", "Ronin-Nue", "Soul Reaper", "Frontline flex"],
      early: ["Treat Ogre Mage as a real Rare pickup, not disposable filler", "Keep casters close enough to benefit from the aura", "Choose Elite Forces at round 15 if the shop odds matter more than discounts"],
      items: ["Mana on Tortola Elder or Storm Shaman", "Magicka Pendant on a physical piece when magic damage is the better damage profile", "Survival items on the aura cluster"],
      positioning: ["Cluster enough units in Ogre Mage aura without feeding full-board AoE", "Protect The Source", "Move casters away from Ronin-Nue jump angles"],
      strongInto: ["Slow front lines", "Boards without silence", "Comps that need one carry to survive"],
      weakInto: ["Assassin access to the aura cluster", "Marine or magic resistance stacking", "Mithril Armor on the target you need to disable"],
      counterPlan: ["Jump Ogre Mage or The Source before the first spell cycle", "Spread to reduce spell splash value", "Use silence on Berserker and active casters since Berserker can now be properly silenced"],
      punishWith: ["watcher-assassin", "egersis-hunter", "druid-super-egg"],
      pivots: ["Divinity Control", "Mage Control", "Watcher Caster"],
      note: "Patch basis: Ogre Mage moved from Common to Rare and now gives nearby allies a chance to cast abilities again while gaining Rage attack speed."
    },
    {
      id: "limit-break-legendary",
      name: "Limit Break Legendary",
      tier: "A",
      style: "Economy Cap",
      difficulty: "Hard",
      timing: "Round 35+",
      score: 86,
      tags: ["Talent", "Level 16", "Legendary"],
      winCondition: "Survive to round 35, choose Limit Break, then turn a larger board cap into overwhelming legendary and control density.",
      core: ["Soul Reaper", "Storm Shaman", "Tsunami Stalker", "Devastator", "Dragon Knight", "Rogue Guard", "Argali Knight", "Any discovered legendary"],
      early: ["Choose economy talents that match your health: Relentless Push when streaking, Quiet Reserve when losing", "At round 15 pick Honor the Worthy for reroll lines or Elite Forces for leveling lines", "Skip weak relic choices for 10-15 gold when economy is the real plan"],
      items: ["Mana on control legendaries", "Defensive items on the main front line", "Damage items on whichever late carry the match pool gives"],
      positioning: ["Spread extra units so the larger board is not one AoE target", "Layer control pieces across multiple rows", "Protect the carry that actually uses the added board space"],
      strongInto: ["Lobbies that let you preserve HP", "Low-pressure economy games", "Comps capped at level 9 or 10"],
      weakInto: ["Hard mid-game pressure", "Assassin snowball", "Odd Call Druid boards that outscale without leveling"],
      counterPlan: ["Pressure before round 35", "Deny win streaks so economy talents produce less value", "Force them to spend before Limit Break matters"],
      punishWith: ["watcher-assassin", "egersis-hunter", "druid-super-egg"],
      pivots: ["Legendary Sustain", "Dragon Legendary", "Ogre Rage Casters"],
      note: "Patch basis: Steam notes add the Talent System, including Limit Break at round 35 to unlock the level cap up to level 16."
    },
    {
      id: "magicka-dragon",
      name: "Magicka Dragon",
      tier: "A",
      style: "Magic Conversion",
      difficulty: "Medium",
      timing: "Item Dependent",
      score: 84,
      tags: ["Magicka Pendant", "Dragon", "Skill Damage"],
      winCondition: "Use Magicka Pendant to convert a high-output carrier into magic damage, while Dragon Knight splash now counting as skill damage opens stronger item and synergy interactions.",
      core: ["Dragon Knight", "Shining Dragon", "Venom", "Winter Chiropteran", "Tortola Elder", "The Source", "Storm Shaman", "Frontline flex"],
      early: ["Do not force without Dragon pieces or Magicka Pendant", "Play strongest upgraded front line until Dragon Knight appears", "Use Elite Forces if you need better odds at higher-cost pieces"],
      items: ["Magicka Pendant on the carrier that needs magic conversion", "Mana on Tortola Elder or Storm Shaman", "Defensive items on the first tank"],
      positioning: ["Keep Dragon Knight away from first disable", "Spread against Watcher-targeted skills", "Aim Storm Shaman into the enemy damage cluster"],
      strongInto: ["Armor-heavy Warriors", "Druid boards relying on armor and damage sharing", "Physical mitigation shells"],
      weakInto: ["Marine or magic resistance", "Assassin jumps", "Silence before first cast"],
      counterPlan: ["Stack magic resistance instead of armor", "Jump The Source or Dragon Knight", "Use Mithril Armor to negate key targeted setup skills"],
      punishWith: ["watcher-assassin", "egersis-hunter", "limit-break-legendary"],
      pivots: ["Dragon Mage", "Ogre Rage Casters", "Legendary Dragon"],
      note: "Patch basis: Magicka Pendant converts damage to magic damage, and Dragon Knight splash damage now counts as skill damage."
    },
    {
      id: "feather-clover",
      name: "Feather Clover",
      tier: "A",
      style: "Evasion Carry",
      difficulty: "Medium",
      timing: "Level 8",
      score: 83,
      tags: ["Feathered", "Assassin", "Four-Leaf Clover"],
      winCondition: "Leverage the Four-Leaf Clover adjustment so Feathered and Assassin synergy effects benefit from item bonuses.",
      core: ["Warpwood Sage", "Wisdom Defender", "Wind Ranger", "Shadowcrawler", "Shining Assassin", "Ronin-Nue", "Razorclaw", "Control flex"],
      early: ["Hold Feathered tanks with Assassin damage pairs", "Prioritize Four-Leaf Clover when offered", "Scout whether the lobby is building magic conversion or pure spell burst"],
      items: ["Four-Leaf Clover on the carry or synergy-critical unit", "Crit and attack speed on Shadowcrawler", "Tank items on Warpwood Sage"],
      positioning: ["Scout carry corners every round", "Split carries against Dragon and Mage boards", "Keep Feathered tanks where they can buy time for jumps"],
      strongInto: ["Hunter backlines", "Single-carry boards", "Physical teams without reliable spell damage"],
      weakInto: ["Magicka Pendant carries", "Large AoE magic", "Mithril Armor and baited target lines"],
      counterPlan: ["Use magic damage instead of physical accuracy checks", "Put expendable bait in both corners", "Disable the Clover holder before synergy value snowballs"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "warrior-frontline"],
      pivots: ["Watcher Assassin", "6 Feathered", "Druid Super Egg"],
      note: "Patch basis: Four-Leaf Clover now lets Feathered and Assassin synergy effects benefit from item bonuses."
    },
    {
      id: "egersis-hunter",
      name: "Egersis Hunter",
      tier: "B",
      style: "Ranged Physical",
      difficulty: "Medium",
      timing: "Level 8",
      score: 80,
      tags: ["Hunter", "Armor Shred", "Tempo"],
      winCondition: "Punish talent-greedy and Druid-greedy players before they reach Odd Call, Super Strange Egg, or Limit Break.",
      core: ["Dwarf Sniper", "Wind Ranger", "Egersis Ranger", "Egersis Prophet", "Tsunami Stalker", "Devastator", "Frontline flex", "Soul Reaper"],
      early: ["Use Hunter pairs with any upgraded tanks", "Choose Relentless Push when streaking", "Take Siphon at round 25 if your chessplayer damage plan needs lifesteal"],
      items: ["Damage on Dwarf Sniper", "Twin Fangs if multiple enemies share the same carry", "Mana on Tsunami Stalker or Devastator"],
      positioning: ["Corner Sniper with bait beside him", "Move corners every round into Assassin lobbies", "Keep control one row ahead of carries"],
      strongInto: ["Greedy leveling", "Druid setups before 3-stars", "Mage boards before they cast"],
      weakInto: ["Watcher Assassin jumps", "Cocoon damage reduction", "Strange Egg damage sharing"],
      counterPlan: ["Jump or target the Hunter backline", "Use Cocoon at round 25 if burst is the lobby problem", "Deploy Strange Egg or tank links to blunt focus fire"],
      punishWith: ["watcher-assassin", "druid-super-egg", "warrior-frontline"],
      pivots: ["Hunter Legendary", "Egersis Control", "Tempo into Limit Break"],
      note: "Patch basis: the Talent System creates more greed windows; Hunters remain useful as a pressure answer even without a direct patch buff."
    },
    {
      id: "warrior-frontline",
      name: "Warrior Frontline",
      tier: "B",
      style: "Stable Tempo",
      difficulty: "Easy",
      timing: "Level 7-8",
      score: 78,
      tags: ["Warrior", "Berserker", "Khan"],
      winCondition: "Use simple armor tempo to survive the new talent economy while deciding whether to push, reroll, or cap late.",
      core: ["Swordman", "Redaxe Chief", "Tusk Champion", "Pirate Captain", "Berserker", "Khan", "Doom Arbiter", "Carry flex"],
      early: ["Buy Warrior pairs and protect health", "Remember Berserker's active can now be silenced", "Treat Khan as a Rare tempo piece after the quality change"],
      items: ["Attack items on Berserker", "Tank items on Pirate Captain or Redaxe Chief", "Mithril Armor on the unit targeted by enemy skills"],
      positioning: ["Spread enough to avoid full Mage value", "Put Khan and Swordman where they influence the first contact", "Protect Berserker from direct silence if he is the carry"],
      strongInto: ["Assassins", "Physical tempo boards", "Unfinished Druid setups"],
      weakInto: ["Magicka Pendant", "Egersis armor reduction", "Caster chains with Ogre Mage"],
      counterPlan: ["Use magic conversion over armor", "Silence Berserker now that it works properly", "Do not let Warriors preserve enough health to reach Limit Break"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "egersis-hunter"],
      pivots: ["Limit Break Legendary", "Hunter Warrior", "Khan Tempo"],
      note: "Patch basis: Khan moved from Legendary to Rare with lower damage profile, and Berserker's ability changed to Active and can be silenced correctly."
    },
    {
      id: "watcher-control",
      name: "Watcher Control",
      tier: "B",
      style: "Targeted Utility",
      difficulty: "Hard",
      timing: "Level 8-9",
      score: 77,
      tags: ["Watcher", "Control", "Utility"],
      winCondition: "Stack unit-targeted disables and item effects so the Watcher change turns one key cast into multi-target disruption.",
      core: ["Ronin-Nue", "Unknown Horror", "Storm Shaman", "Soul Reaper", "Taboo Witcher", "Ogre Mage", "Frontline flex", "Carry flex"],
      early: ["Start from Ronin-Nue or Unknown Horror shops", "Do not force Watcher if the lobby has Mithril Armor everywhere", "Pick Elite Forces if higher-cost control pieces are the plan"],
      items: ["Targeted active items on reliable casters", "Mana on Storm Shaman or Soul Reaper", "Defensive items on the control front line"],
      positioning: ["Aim targeted skills away from bait units", "Spread to avoid losing all control pieces at once", "Move Ronin-Nue to threaten the highest-value target"],
      strongInto: ["Single carry comps", "Boards relying on one protected caster", "Low-bait backlines"],
      weakInto: ["Mithril Armor", "Wide summon boards", "Druid damage sharing"],
      counterPlan: ["Use expendable units to absorb extra targeted effects", "Put Mithril Armor on the high-value target", "Overwhelm with summons or linked Egg units"],
      punishWith: ["druid-super-egg", "summon-war-horn", "feather-clover"],
      pivots: ["Watcher Assassin", "Ogre Rage Casters", "Limit Break Legendary"],
      note: "Patch basis: Watcher's old +1 item ability effect was removed, then replaced with a broader extra-target effect for unit-targeted or item abilities cast on enemies."
    },
    {
      id: "summon-war-horn",
      name: "Summon War Horn",
      tier: "B",
      style: "Summon Pressure",
      difficulty: "Medium",
      timing: "Mid Game",
      score: 75,
      tags: ["Summon", "War Horn", "Tempo"],
      winCondition: "Use summon pressure as a practical answer to Watcher target lines and single-target carries, especially if the lobby lacks AoE.",
      core: ["Razorclaw", "Werewolf", "Poisonous Worm", "Tusk Champion", "Pirate Captain", "Berserker", "Soul Reaper", "Control flex"],
      early: ["Play summons when pairs are natural", "Choose Relentless Push if summons are preserving a streak", "Skip weak relic choices for gold when you need tempo"],
      items: ["War Horn on a reliable summoner", "Damage items on Berserker or carry flex", "Mana on Pirate Captain or Soul Reaper"],
      positioning: ["Leave room for summons", "Avoid clumping into Mage splash", "Put expendable summoned value between Watcher threats and your real carry"],
      strongInto: ["Single-target Watcher lines", "Hunter boards without AoE", "Low-damage stall comps"],
      weakInto: ["Dragon Mage", "Devastator", "Ogre caster chains"],
      counterPlan: ["Clear summons with AoE", "Kill summoners before War Horn value lands", "Use Strange Egg links so summons do not isolate priority targets"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "druid-super-egg"],
      pivots: ["Druid Super Egg", "Warrior Frontline", "Beast Warrior"],
      note: "Patch basis: not the headline of the Steam patch, but summon boards remain a useful counter-shape into the new Watcher single-target pressure."
    },
    {
      id: "insect-midgame-swarm",
      name: "Insect Midgame Swarm",
      tier: "A",
      style: "Community Meta",
      difficulty: "Medium",
      timing: "Mid Game",
      score: 85,
      tags: ["Insectoid", "Civet", "Summon", "Reddit"],
      winCondition: "Use the post-update Insect consistency to flood the mid game with extra bodies, then let summons and duplicate-piece pressure protect the real carry.",
      core: ["Civet", "Insectoid pair", "Duplicate non-Insect front line", "Poisonous Worm", "Razorclaw", "Werewolf", "Control flex", "Carry flex"],
      early: ["Hold duplicate non-Insect pairs when the Insect opener is natural", "Keep one duplicate safer so the dying copy can trigger swarm value", "Do not force it into lobbies already stacking AoE"],
      items: ["War Horn on a reliable summoner", "Tank items on the surviving duplicate or main front line", "Sustain or cleave on the real carry"],
      positioning: ["Split duplicate pairs so one dies first and one survives", "Leave board space for summons to matter", "Keep the real carry away from the first control lane"],
      strongInto: ["Single-target Watcher lines", "Hunters without AoE", "Greedy boards that need time to stabilize"],
      weakInto: ["Dragon Mage", "Ogre caster chains", "High-sustain Glacier or Warlock carries"],
      counterPlan: ["Use wide AoE to clear summons before they stall the fight", "Focus the surviving duplicate to deny repeated Insect value", "Bring lifesteal or spell lifesteal so summon chip damage feeds recovery"],
      punishWith: ["magicka-dragon", "ogre-rage-casters", "warrior-frontline"],
      pivots: ["Summon War Horn", "Beast Warrior", "Druid Super Egg"],
      note: "Community signal: recent r/AutoChess discussion says post-update Insect feels more consistent and easier through the mid game; treat this as a meta watch item rather than an official tier placement.",
      sourceLabel: "r/AutoChess: Insect synergy after update",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1tp05dl/insect_synergy_after_update/"
    },
    {
      id: "knight-cannon-granny",
      name: "Knight Cannon Granny",
      tier: "A",
      style: "Community Meta",
      difficulty: "Medium",
      timing: "Level 8-9",
      score: 84,
      tags: ["Knight", "Cannon Granny", "Carry", "Reddit"],
      winCondition: "Let the Knight shell buy enough time for Cannon Granny to shred the enemy front line and carry through sustained physical damage.",
      core: ["Cannon Granny", "Lightblade Knight", "Hell Knight", "Argali Knight", "Dragon Knight", "Soul Reaper", "Control flex", "Defensive support"],
      early: ["Play upgraded Knight pairs and preserve health", "Use any temporary ranged carry until Cannon Granny appears", "Scout for Egersis players before committing all damage items"],
      items: ["Attack speed and damage on Cannon Granny", "Tank items on the Knight most likely to take first contact", "Mana or control items on the support slot"],
      positioning: ["Keep Cannon Granny protected but not boxed in by low-value units", "Move the carry away from Assassin jump lanes", "Spread Knights enough to avoid one spell cycle deciding the round"],
      strongInto: ["Physical tempo boards", "Assassins that cannot reach the carry", "Low-burst front-to-back comps"],
      weakInto: ["Egersis armor reduction", "Magicka Pendant spell conversion", "Watcher jumps onto Cannon Granny"],
      counterPlan: ["Shred armor or bypass it with magic conversion", "Jump or target Cannon Granny before shields stabilize", "Use bait units so the Knight player cannot line up clean front-to-back damage"],
      punishWith: ["egersis-hunter", "magicka-dragon", "watcher-assassin"],
      pivots: ["Warrior Frontline", "Limit Break Legendary", "Dragon Knight Carry"],
      note: "Community signal: a recent r/AutoChess S36 post highlights Knight with Cannon Granny carry as a top meta threat; the source is title-level, so verify the exact final board in your own games.",
      sourceLabel: "r/AutoChess: Knight Cannon Granny S36",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1tgg9er/knight_is_the_most_broken_meta_in_s36_cannon/"
    },
    {
      id: "cave-divinity-mountain",
      name: "Cave Divinity Mountain",
      tier: "B",
      style: "Community Meta",
      difficulty: "Hard",
      timing: "Level 8-9",
      score: 81,
      tags: ["Cave Clan", "Divinity", "Mountain", "Reddit"],
      winCondition: "Combine a bulky Cave Clan core with Divinity tempo so Mountain can keep casting, soaking, and turning long fights.",
      core: ["Mountain", "Redaxe Chief", "Swordman", "Skull Hunter", "God of War", "God of Thunder", "The Source", "Storm Shaman"],
      early: ["Start from Cave Clan pairs when they are upgraded naturally", "Add Divinity pieces when the board can still support the synergy plan", "Keep an alternate Warrior or control line open if Mountain is contested"],
      items: ["Tank and sustain on Mountain", "Mana on The Source or Storm Shaman", "Damage on the temporary carry until Mountain is ready"],
      positioning: ["Put Mountain where he takes contact without being instantly isolated", "Protect The Source from backline jumps", "Shift Storm Shaman toward the enemy carry cluster"],
      strongInto: ["Low-burst physical boards", "Summon pressure without enough damage", "Assassins after Mountain is itemized"],
      weakInto: ["Egersis armor shred", "High-roll Legendary caps", "Pure magic burst before sustain begins"],
      counterPlan: ["Pressure it before the Cave and Divinity pieces are both online", "Use armor reduction or magic conversion instead of fighting through raw HP", "Jump The Source so the cooldown engine slows down"],
      punishWith: ["egersis-hunter", "magicka-dragon", "watcher-assassin"],
      pivots: ["Warrior Frontline", "Limit Break Legendary", "Ogre Rage Casters"],
      note: "Community signal: a recent r/AutoChess S36 post calls Cave Clan plus Divinity with Mountain carry back to meta; this entry is a practical sketch from the title signal, not a full written guide.",
      sourceLabel: "r/AutoChess: Cave Divinity Mountain S36",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1t63bsa/back_to_meta_in_s36_cave_clan_divinity_with/"
    },
    {
      id: "beast-shining-assassin",
      name: "6 Beast Shining Assassin",
      tier: "B",
      style: "Community Meta",
      difficulty: "Medium",
      timing: "Level 8",
      score: 80,
      tags: ["Beast", "Assassin", "Shining Assassin", "Reddit"],
      winCondition: "Use the 6 Beast damage engine and summon traffic to amplify Shining Assassin as the main backline killer.",
      core: ["Shining Assassin", "Tusk Champion", "Werewolf", "Razorclaw", "Poisonous Worm", "Unicorn", "Shadowcrawler", "Control flex"],
      early: ["Open with Beast pairs and any upgraded front line", "Hold Shining Assassin pieces without tanking your economy", "Use 3 Assassin as the bridge before the full Beast package is ready"],
      items: ["Damage, crit, and attack speed on Shining Assassin", "War Horn on a summoner when available", "Defensive utility on the unit most likely to bait control"],
      positioning: ["Jump Shining Assassin toward the highest-value backline target", "Leave room for summons to block enemy movement", "Move the carry every round into players holding targeted disables"],
      strongInto: ["Greedy caster boards", "Single-carry backlines", "Low-AoE Hunter setups"],
      weakInto: ["Warrior armor", "Mithril Armor and targeted control", "Dragon Mage splash"],
      counterPlan: ["Armor up and bait the Assassin jump", "Use AoE to remove summons before Beast damage stacks", "Disable Shining Assassin before she resets the fight"],
      punishWith: ["warrior-frontline", "watcher-control", "magicka-dragon"],
      pivots: ["Feather Clover", "Watcher Assassin", "Summon War Horn"],
      note: "Community signal: a recent r/AutoChess S36 post presents 6 Beast with Shining Assassin carry as an easy ranked build; source detail is title-level, so treat it as a lobby test candidate.",
      sourceLabel: "r/AutoChess: 6 Beast Shining Assassin S36",
      sourceUrl: "https://www.reddit.com/r/AutoChess/comments/1sqidks/easy_build_for_ranked_in_s36_6_beast_with_shining/"
    }
  ]
};
